apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: practice-ebs-pv
provisioner: kubernetes.io/aws-ebs
parameters:
 type: gp2
 iopsPerGB: "10"
 fsType: ext4
allowVolumeExpansion: true
reclaimPolicy: Retain
