apiVersion: v1
kind: PersistentVolume
metadata:
 name: practice-pv-rwo
spec:
 storageClassName: local
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 3Gi
 hostPath:
  path: "/home/ubuntu"
 persistentVolumeReclaimPolicy: Delete
