apiVersion: v1
kind: Pod
metadata:
 name: practice-pod-pvc
spec:
 containers: 
  - name: nginx-practice-pvc
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvc-vol
      mountPath: "/var/lib/nginx"
 volumes:
  - name: pvc-vol
    persistentVolumeClaim:
      claimName: practice-pvc
