apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: practice-rb
 namespace: practice-ns
subjects:
 - kind: ServiceAccount
   name: practice-sa
roleRef:
 kind: Role
 name: practice-role
