apiVersion: v1
kind: Service
metadata:
 name: practice-headless
 namespace: practice-ns
spec:
 selector:
   practice: test
 clusterIP: None
 ports:
 - protocol: TCP
   port: 30003
   targetPort: 8080
