apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: jenkins-admin
roleRef:
   kind: ClusterRole
   name: jenkins-admin
subjects:
 - kind: ServiceAccount
   name: jenkins-admin
   namespace: devops-tools

