Description: This template is to create an EC2 instance in ap-south-1
Resources:
  MyFirst-CF-SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescripton: Security group for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/16
        - IpProtocol: ssh
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/16
        - IpProtocol: http
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/16
    
  Myfirst-CF-EC2:
    Type: AWS::EC2::Insatnce
    Properties:
      ImageId:
      InstanceType: t2.micro
      KeyName: cf_ec2_key
      SecurityGroupIds:
        - !Ref MyFirst-CF-SG
