Description: This template is to create an EC2 instance in ap-south-1
Resources:
  MyFirstCFSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/16
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/16
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/16
    
  MyfirstCFEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09298640a92b2d12c
      InstanceType: t2.micro
      KeyName: cf_ec2_key
      SecurityGroupIds:
        - !Ref MyFirstCFSG
