apiVersion: v1
kind: Service
metadata: 
 name: my-service
 namespace: my-ns-2
spec:
    selector:
                env: dev
    type: ClusterIP
    ports:
            - protocol: TCP
              port: 30002
              targetPort: 8080

