---
apiVersion: v1
kind: Pod
metadata:
  name: my-cm-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: CURRENT-ENV
          valueFrom:
            configMapKeyRef:
              name: my-cm
              key: current-env
        - name: APP
          valueFrom:
            configMapKeyRef:
              name: my-cm
              key: app

