apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset


spec:
  template:
   metadata:
    labels:
            env: dev
   spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
