apiVersion: apps/v1
kind: DaemonSet
metadata:
        name: my-daemonset
spec:
 selector:
        matchLabels:
                env: dev
 template:
        metadata:
                labels:
                 env: dev
        spec:
                        containers:
                                - name: my-daemonset
                                  image: nginx
                                  ports:
                                          - containerPort: 80

