apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: my_deamonset
selector:
 matchlabels:
  environment: dev
spec:
 labels:
 environment: dev
 template:
 containers:
 - name: nginx
   image: nginx
   ports:
   - containerport: 80