apiVersion: apps/v1
kind: Deployment
metadata:
	name: my_deployment 

spec:
	replicas: 5
	labels:
		environment: dev
	selector:
		matchlabels:
			environment: dev
	template:
		containers:
		-name: nginx
		image: nginx
		ports:
			-containerport: 80