---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-deploy
spec:
  selector:
    matchLabels:
      app: busy
  replicas: 2
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: headless
spec:
  selector:
    app: busy
  clusterIP: None
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 8080

