apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: ip-app-statefulset
 namespace: my-ns-2
spec:
 replicas: 4
 selector:
  matchLabels: 
   app: ip-app-statefulset
 template:
  metadata:
   labels:
    app: ip-app-statefulset
  spec:
   containers:
    - name: ip-app
      image: nginx
      ports:
      - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
 name: my-headless-service
 namespace: my-ns-2
spec:
 selector:
  app: ip-app-statefulset
 clusterIP: None
 ports:
  - protocol: TCP
    port: 30002
    targetPort: 30004
