---
apiVersion: v1
kind: Service
metadata:
  name: my-service-np
spec:
  selector:
    env: dev
  type: NodePort
  ports:
    - protocol: TCP
      port: 30006
      targetPort: 80
      nodePort: 30010

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-np
spec:
  replicas: 5
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      env: dev

